# Book settings
# Learn more at https://jupyterbook.org/customize/config.html

title: Python para TIC II
author: Alberto Durán Pérez
copyright: "2025"  # Copyright year to be placed in the footer
logo: logo.png
only_build_toc_files: true
language: "es"

# Force re-execution of notebooks on each build.
# See https://jupyterbook.org/content/execute.html
execute:
  execute_notebooks: auto

# Define the name of the latex output file for PDF builds
latex:
  latex_documents:
    targetname: book.tex


launch_buttons:
  notebook_interface: "jupyterlab" # The interface interactive links will activate ["classic", "jupyterlab"]
  binderhub_url: "https://mybinder.org"
  colab_url: "https://colab.research.google.com"
  deepnote_url: "https://deepnote.com"
  thebe: true

# Add a bibtex file so that we can create citations
bibtex_bibfiles:
  - references.bib

# Information about where the book exists on the web
repository:
  url: https://github.com/citius70/curso_python_tic2/ # Online location of your book
#  path_to_book:  # Optional path to your book, relative to the repository root
  branch: gb-pages # Which branch of the repository should be used when creating links (optional)

# Add GitHub buttons to your book
# See https://jupyterbook.org/customize/config.html#add-a-link-to-your-repository
html:
  use_issues_button: true
  use_repository_button: true
  use_edit_page_button: true # Whether to add an "edit this page" button to pages. If `true`, repository information in repository: must be filled in
  use_multitoc_numbering: true # Continuous numbering across parts/chapters
  home_page_in_navbar: true # Whether to include your home page in the left Navigation Bar

comments:
    hypothesis              : false
    utterances              : false
announcement                : "" # A banner announcement at the top of the site.



launch_buttons:
  notebook_interface: "classic" # or "jupyterlab"
  colab_url: "https://colab.research.google.com"
